export const ADD_TASK='ADD_TASK';
export const TOOGLE_COMPLETE='TOGGLE_COMPLETE'
export const DELETE_TASK='DELETE_TASK'
export const EDIT_TASK='EDIT_TASK'
export const DELETE_ALL_TASKS='DELETE_ALL_TASKS'
export const DELETE_COMPLETED_TASKS='DELETE_COMPLETED_TASKS'
export const DELETE_UNCOMPLETED_TASKS='DELETE_UNCOMPLETED_TASKS'
export const MARK_ALL_TASKS_AS_COMPLETE='MARK_ALL_TASKS_AS_COMPLETE'